In [2]:
import numpy as np
python_list = [1,2,3,4,5,6,7,8,9,10]
numpy_array = np.array(python_list)
print(numpy_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#creating an array using linspace funtion
A = np.linspace(0,2,20)
print(A)

[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]


In [10]:
#creating a 2d array from a python list
second_list = [[1,2,3],[4,5,6],[7,8,9]]
d2_array = np.array(second_list)
print(d2_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#creating a numpy array with arange function
array = np.arange(0,18,3)
print(array)

[ 0  3  6  9 12 15]


In [19]:
#creating a numpy array with zeros
zeros_list = np.zeros((3,6))
print(zeros_list)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
#creating a numpy array with ones
ones_list = np.ones([3,3])
print(ones_list)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
#creating an identity matrix 
matrix = np.eye(6)
matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
#generating an array of random numbers
random = np.random.rand(3,6)
random

array([[0.8406909 , 0.51161774, 0.12315064, 0.51549409, 0.8840647 ,
        0.46090531],
       [0.35598854, 0.31194741, 0.35377391, 0.25744872, 0.33481621,
        0.32842926],
       [0.91028115, 0.44712345, 0.75219987, 0.3625924 , 0.21600845,
        0.70899552]])

In [28]:
random = np.random.randn(3,6)
random

array([[-0.59050869, -0.33660527,  0.30222786, -0.77933491, -0.60934152,
        -1.01131438],
       [-2.77000052, -0.36190143,  0.56714976,  0.26793736, -1.21261597,
         1.72003492],
       [-0.87629284, -0.55228337,  0.71431457, -0.62491798,  0.31074339,
        -1.03537756]])

In [31]:
random = np.random.randint(0,20,50)
random

array([ 6,  0,  1,  6,  4, 14,  8,  1,  6, 16, 10, 13,  1, 10,  5,  1,  5,
        0,  3,  6,  7, 13, 13, 19,  8, 14,  6, 19,  2,  7,  3,  1, 18,  5,
       11, 16, 14,  4, 15,  5, 14,  6, 16,  4,  9,  0, 12,  9,  3, 18])

In [37]:
random = np.random.randint(0,20,25)
random
random.reshape(5,5)

array([[ 1, 12, 12, 12,  4],
       [ 7,  9,  7, 12,  9],
       [13, 16,  0, 17,  9],
       [ 7,  2, 14,  9, 15],
       [ 4,  5,  8,  7,  5]])

In [38]:
#locating the minimum and maximum value 
random = np.random.randint(0,20,25)
random
print(random.reshape(5,5))
print(random.max())
print(random.min())
print(random.argmax())
print(random.argmin())

[[ 8 12 15 15  5]
 [ 9 18  9 10 18]
 [15 12  7 16 11]
 [11  5 12 11  0]
 [ 6  8 13 10 13]]
18
0
6
19


In [41]:
#indexing elements from a numpy array
array = np.arange(0,100,10)
print(array[6])
#for a range of values
print(array[3:7])
#for a 2d array
array_2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array_2[2],[1])
print(array_2[:1,:2])
print(array_2[2])

60
[30 40 50 60]
[70 80 90] [1]
[[10 20]]
[70 80 90]


In [5]:
array = np.arange(0,100,10)
print(array>20)
boolean = array>20
boolean_2 = array<10
print(array[boolean])



[False False False  True  True  True  True  True  True  True]
[30 40 50 60 70 80 90]


In [5]:
#Assignment
#1
import numpy as np
one_dim_array = np.arange(0,30,2)
one_dim_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [6]:
two_dim_array = np.array([[2,3,4,11],[5,6,7,12],[8,9,10,13]])
print(two_dim_array)
print(two_dim_array.reshape(6,2))



[[ 2  3  4 11]
 [ 5  6  7 12]
 [ 8  9 10 13]]
[[ 2  3]
 [ 4 11]
 [ 5  6]
 [ 7 12]
 [ 8  9]
 [10 13]]


In [7]:
four_array = np.full((4,4),4)
four_array

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])